### ISSUE TITLE
set X-Frame-Options SAMEORIGIN

### ISSUE THREAD

**Issue by markusstrasser** [OasysFoundation/Oasys-Backend#4]
Our server needs to allow iframes to embed content that we host. Currently we get permission denied because of X-FRAME block.

**Comment by frogg** [comment]
looks like we can change that in the `firebase.json`:

```
"headers": [{
   "source": "**/*",
   "headers": [
     {"key": "X-Content-Type-Options", "value": "nosniff"},
     {"key": "X-Frame-Options", "value": "SAMEORIGIN"},
     {"key": "X-UA-Compatible", "value": "ie=edge"},
     {"key": "X-XSS-Protection", "value": "1; mode=block"}
   ]
 }]
```

Source:
https://stackoverflow.com/a/46762121

**Comment by frogg** [comment]
@cocokiri can you check again? I've added the new SAMEORIGIN policy to our project so I hope it works now.
